connections:
  unixSocketPath : ""
  useUnix: false
  tcpIp: ""

  tcpPort: 21853
  tcpPortRandom: false
  useTcp: false

  httpIp: ""
  httpPort: 21854
  useHttp: false

  connectionKey: "vavavava"
btccore:
  rpcIp : ""
  rpcPort: 0
  rpcUserName : ""
  rpcPassowrd : ""
  # Needed to track transactions
  zmqpubhashblock : ""
  
lnd:
  #can bet set in the API at runtime.
  macroon: null
  restPort: 0
  restIp: "127.0.0.1"
  # Is read on startup
  tlsPath : ""
  # Can be set at runtime
  walletPassword : ""

db:
  #defaults to be relative to the executable
  sqliteDbPath : "transactions.db"
  username: "alba"
  password: "sort"
  database: ""
btcConfig:
  # The time for a given deposit to expire
  depositTimeOutSeconds : 7200
  #Wallet password sent at runtime over RCP.
  walletName : "MyClientWallet"

  #Can be changed at runtime
  defaultBtcip: ""
  defaultBtcport: 19773

  #Change to set how often you want to check for deposits and withdrawals
  depositWithdrawalPollSeconds : 300

  # Allows you to send 'individual' withdrawals which are sent immediately, with higher feels for the user
  enableInvdividualWithdrawals : true
debug:
  debugPath: "./debug_output.txt"
  enableDebug: true
callbacks:
  discord:
    discordToken: ""
    discordPort: 0
    defaultChannel: ""
    useDefaultChannel: false
    callbacks:
      deposits:
        noChange: ""
        fundingIncreased: ""
        expired: ""
        fullyFunded: ""
      exceptions:
        errorUpdatingRow: ""
        notEnoughFunds: ""
        failedToSubmitRawTx: ""
        failedToCreateTx: ""
        multipleCoinsInWithdrawal: ""
        incorrectCoinInWithdrawal: ""
      channels:
        channelCreated: ""
        invoicedPaid: ""
        channelOpenTxConfirm: ""
        channelClosed: ""
        channelCloseTxConfirm: ""
      withdrawals:
        withdrawalCreated: ""
        groupWithdrawalFulfilled: ""
        singleWithdrawalCreated: ""
        withdrawalTxConfirmed: ""
      btc: {newBlockConfirmed: ""}
      xmr:
        newBlockConfirmed: ""
        newUTXOUnlocked: ""
  smtp:
    username: ""
    password: ""
    port: 0
    address: ""
    callbacks:
      deposits:
        noChange: ""
        fundingIncreased: ""
        expired: ""
        fullyFunded: ""
      exceptions:
        errorUpdatingRow: ""
        notEnoughFunds: ""
        failedToSubmitRawTx: ""
        failedToCreateTx: ""
        multipleCoinsInWithdrawal: ""
        incorrectCoinInWithdrawal: ""
      channels:
        channelCreated: ""
        invoicedPaid: ""
        channelOpenTxConfirm: ""
        channelClosed: ""
        channelCloseTxConfirm: ""
      withdrawals:
        withdrawalCreated: ""
        groupWithdrawalFulfilled: ""
        singleWithdrawalCreated: ""
        withdrawalTxConfirmed: ""
      btc: {newBlockConfirmed: ""}
      xmr:
        newBlockConfirmed: ""
        newUTXOUnlocked: ""
    defaultMail: ""
    useDefaultMail: false
    useTLS: false
    useAuth: false
  tcp:
    ip: ""
    port: ""
    broadcastOverRecievingTcp: false
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  unixSocket:
    location: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  http:
    endpoint: ""
    auth: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  namedPipe:
    path: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false


