connections:
  unixSocketPath: ""
  useUnix: false
  tcpIp: ""
  tcpPort: 0
  tcpPortRandom: false
  useTcp: false
  httpIp: ""
  httpPort: 0
  useHttp: false
  connectionKey: ""
db:
  #defaults to be relative to the executable
  sqliteDbPath : "transactions.db"
  username: "alba"
  password: "sort"
  database: ""
btcConfig:
  depositTimeOutSeconds: 72000
  walletName: "albassort"
  walletPassword: "password"
  depositWithdrawalPollSeconds: 1
  enableInvdividualWithdrawals: true
debug:
  debugPath: ""
  enableDebug: false
callbacks:
  discord:
    discordToken: ""
    discordPort: 0
    defaultChannel: ""
    useDefaultChannel: false
    callbacks:
      deposits:
        noChange: ""
        fundingIncreased: ""
        expired: ""
        fullyFunded: ""
      exceptions:
        errorUpdatingRow: ""
        notEnoughFunds: ""
        failedToSubmitRawTx: ""
        failedToCreateTx: ""
        multipleCoinsInWithdrawal: ""
        incorrectCoinInWithdrawal: ""
      channels:
        channelCreated: ""
        invoicedPaid: ""
        channelOpenTxConfirm: ""
        channelClosed: ""
        channelCloseTxConfirm: ""
      withdrawals:
        withdrawalCreated: ""
        groupWithdrawalFulfilled: ""
        singleWithdrawalCreated: ""
        withdrawalTxConfirmed: ""
      btc: {newBlockConfirmed: ""}
      xmr:
        newBlockConfirmed: ""
        newUTXOUnlocked: ""
  smtp:
    username: ""
    password: ""
    port: 0
    address: ""
    callbacks:
      deposits:
        noChange: ""
        fundingIncreased: ""
        expired: ""
        fullyFunded: ""
      exceptions:
        errorUpdatingRow: ""
        notEnoughFunds: ""
        failedToSubmitRawTx: ""
        failedToCreateTx: ""
        multipleCoinsInWithdrawal: ""
        incorrectCoinInWithdrawal: ""
      channels:
        channelCreated: ""
        invoicedPaid: ""
        channelOpenTxConfirm: ""
        channelClosed: ""
        channelCloseTxConfirm: ""
      withdrawals:
        withdrawalCreated: ""
        groupWithdrawalFulfilled: ""
        singleWithdrawalCreated: ""
        withdrawalTxConfirmed: ""
      btc: {newBlockConfirmed: ""}
      xmr:
        newBlockConfirmed: ""
        newUTXOUnlocked: ""
    defaultMail: ""
    useDefaultMail: false
    useTLS: false
    useAuth: false
  tcp:
    ip: ""
    port: ""
    broadcastOverRecievingTcp: false
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  unixSocket:
    location: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  http:
    endpoint: ""
    auth: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false
  namedPipe:
    path: ""
    callbacks:
      deposits:
        noChange: false
        fundingIncreased: false
        expired: false
        fullyFunded: false
      exceptions:
        errorUpdatingRow: false
        notEnoughFunds: false
        failedToSubmitRawTx: false
        failedToCreateTx: false
        multipleCoinsInWithdrawal: false
        incorrectCoinInWithdrawal: false
      channels:
        channelCreated: false
        invoicedPaid: false
        channelOpenTxConfirm: false
        channelClosed: false
        channelCloseTxConfirm: false
      withdrawals:
        withdrawalCreated: false
        groupWithdrawalFulfilled: false
        singleWithdrawalCreated: false
        withdrawalTxConfirmed: false
      btc: {newBlockConfirmed: false}
      xmr:
        newBlockConfirmed: false
        newUTXOUnlocked: false

btcCore:
  rpcIp: "http://127.0.0.1"
  rpcPort: 18011
  rpcUserName: "user1"
  rpcPassword: "password1"
  zmqpubhashblock: ""
lnd:
  macroon: ""
  restPort: 0
  restIp: ""
  tlsPath: ""
  walletPassowrd: ""
